using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Reflection;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using SonicFX.Menu;

public static class SoniaVerify
{
    const string Folder="Assets/Characters/Sonia";
    static string Out => Path.Combine(Path.GetTempPath(),"SonicFXSonia")+Path.DirectorySeparatorChar;
    [MenuItem("Sonic FX/Personnages/Verifier Sonia")]
    public static void Run()
    {
        if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Quitter Play avant les tests Sonia.");
        Directory.CreateDirectory(Out);var report=new StringBuilder();var scene=EditorSceneManager.NewPreviewScene();
        try {
            var original=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/BumperEngineV1/PlayerPrefabs/PO_ModernSonic.prefab").GetComponentInChildren<PlayerBhysics>(true);
            var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(Folder+"/Sonia.prefab");Require(prefab,"Prefab Sonia installe");
            var root=(GameObject)PrefabUtility.InstantiatePrefab(prefab,scene);var player=root.GetComponentInChildren<PlayerBhysics>(true);var actions=player.GetComponent<ActionManager>();var animator=actions.Action00.CharacterAnimator;animator.enabled=false;
            Require(player.TopSpeed==original.TopSpeed&&player.MaxSpeed==original.MaxSpeed,"Vitesses Sonic Moderne conservees");Require(actions.AvailableAbilities==SonicAbility.All,"Toutes les capacites debloquees");
            var sounds=root.GetComponentInChildren<SonicSoundsControl>(true);Require(sounds.CombatVoiceClips.Length==0&&sounds.JumpingVoiceClips.Length==0&&sounds.PainVoiceClips.Length==0,"Aucune voix");Require(sounds.Source4&&sounds.Source4.mute&&sounds.Source4.clip==null&&!sounds.Source4.playOnAwake,"Source voix silencieuse");Require(sounds.Jumping&&sounds.RingLoss&&sounds.Spin,"Bruitages conserves");
            Require(animator.avatar&&animator.avatar.isValid,"Avatar Sonia valide");var model=animator.transform.Find("SoniaRig");Require(model,"Modele Sonia");
            var originalModel=AssetDatabase.LoadAssetAtPath<GameObject>(Folder+"/sonia_the_hedgehog.glb");var sourceSkins=originalModel.GetComponentsInChildren<SkinnedMeshRenderer>(true);var skins=model.GetComponentsInChildren<SkinnedMeshRenderer>(true);
            Require(skins.Length==sourceSkins.Length,"Toutes les parties du modele importe conservees");
            foreach(var skin in skins){var source=sourceSkins.FirstOrDefault(s=>s.sharedMesh==skin.sharedMesh);Require(source,"Maillage et UV d'origine");for(int i=0;i<source.sharedMaterials.Length;i++){var mat=source.sharedMaterials[i];var dst=skin.sharedMaterials[i];Require(dst&&dst.shader&&!ShaderUtil.ShaderHasError(dst.shader),"Materiau Sonia valide");if(mat.HasProperty("baseColorTexture")&&mat.GetTexture("baseColorTexture"))Require(dst.mainTexture==mat.GetTexture("baseColorTexture")&&(mat.name=="Material.024"?(dst.mainTextureScale==new Vector2(1,-1)&&dst.mainTextureOffset==new Vector2(0,.75f)):(dst.mainTextureScale==mat.GetTextureScale("baseColorTexture")&&dst.mainTextureOffset==mat.GetTextureOffset("baseColorTexture"))),"Texture et placement d'origine");}}
            var face=model.GetComponentsInChildren<Transform>(true).First(t=>t.name=="Head_Amy_skeleton");var facial=face.GetComponentsInChildren<Transform>(true).Where(t=>t!=face).Select(t=>new LocalPose(t)).ToArray();var neutralRotation=face.rotation;
            var foot=model.GetComponentsInChildren<Transform>(true).First(t=>t.name=="Foot_L_Amy_skeleton");var clips=AssetDatabase.FindAssets("t:AnimationClip",new[]{Folder+"/Animations"}).Select(AssetDatabase.GUIDToAssetPath).Where(p=>p.EndsWith(".anim")).Select(AssetDatabase.LoadAssetAtPath<AnimationClip>).ToArray();Require(clips.Length>=19,"Bibliotheque complete ModernSonic");Require(animator.runtimeAnimatorController.animationClips.Distinct().Count()>=15,"Tous les etats du controleur Moderne");
            foreach(var clip in clips){
                Require(!AnimationUtility.GetAnimationEvents(clip).Any(e=>e.functionName.Contains("Voice")),"Aucun evenement voix "+clip.name);
                foreach(var binding in AnimationUtility.GetCurveBindings(clip)){if(binding.type==typeof(Transform))Require(animator.transform.Find(binding.path),"Chemin animation "+clip.name);Require(!facial.Any(p=>AnimationUtility.CalculateTransformPath(p.t,animator.transform)==binding.path),"Visage non retargete");}
                int frames=Mathf.Max(1,Mathf.CeilToInt(clip.length*30));for(int frame=0;frame<=frames;frame++){clip.SampleAnimation(animator.gameObject,clip.length*frame/frames);foreach(var pose in facial)pose.Check(clip.name);}
                foreach(float time in new[]{0,.25f,.5f,.75f,1}){clip.SampleAnimation(animator.gameObject,clip.length*time);var bounds=Bounds(model.gameObject);Require(!float.IsNaN(bounds.size.sqrMagnitude)&&bounds.size.magnitude<14,"Geometrie stable "+clip.name);}
                report.AppendLine("PASS animation "+clip.name);
            }
            var appearance=player.GetComponent<SoniaAppearance>();Require(appearance&&appearance.BodySkins.SequenceEqual(skins)&&appearance.SpinBall,"Affichage corps/boule");Require(actions.Action03.PlayerSkin.SequenceEqual(skins)&&(!actions.Action08||actions.Action08.PlayerSkin.SequenceEqual(skins))&&player.GetComponent<HurtControl>().SonicSkins.SequenceEqual(skins),"References des parties du corps");
            var amy=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/BumperEngineV1/PlayerPrefabs/PO_Amy.prefab").GetComponentInChildren<Action03_SpinDash>(true);Require(appearance.SpinBall.sharedMesh==amy.SpinDashBall.sharedMesh&&appearance.SpinBall.sharedMaterials.SequenceEqual(amy.SpinDashBall.sharedMaterials),"Boule Amy et ses materiaux");Require(actions.Action03.BallAnimator.transform==appearance.SpinBall.transform.parent,"Animateur boule Amy");
            var hurt=player.GetComponent<HurtControl>();foreach(var state in new[]{0,1,3,6,8,4,0}){actions.Action=state;player.isRolling=false;hurt.IsInvencible=false;actions.Action03.ResetSpinDashVariables();appearance.RefreshVisuals(0);bool ball=state==1||state==3||state==6||state==8;Require(appearance.SpinBall.enabled==ball&&skins.All(s=>s.enabled==!ball),"Affichage action "+state);}
            actions.Action=4;hurt.IsHurt=true;hurt.IsInvencible=true;bool visible=false,hidden=false;for(int i=0;i<20;i++){hurt.ToggleSkin(i%2==0);actions.Action03.ResetSpinDashVariables();appearance.RefreshVisuals(i*.05f+.01f);Require(!appearance.SpinBall.enabled&&skins.All(s=>s.enabled==skins[0].enabled),"Clignotement synchrone");visible|=skins[0].enabled;hidden|=!skins[0].enabled;}Require(visible&&hidden,"Deux phases du clignotement");hurt.IsInvencible=false;hurt.IsHurt=false;actions.Action=0;appearance.RefreshVisuals(0);Require(skins.All(s=>s.enabled),"Corps entier apres degats");
            report.AppendLine("PASS corps entier apres degats et boule Amy.");
            foreach(var name in new[]{"Idle","Run","MachRun","Rise","Damage","Roll","Rail_Med[i]"}){var clip=clips.First(c=>c.name==name);clip.SampleAnimation(animator.gameObject,clip.length*.3f);Render(animator.gameObject,Out+name+".png");RenderFace(animator.gameObject,Out+name+"-face.png",neutralRotation);}
            actions.Action=1;appearance.RefreshVisuals(0);actions.Action03.BallAnimator.Rebind();actions.Action03.BallAnimator.Update(.3f);Render(animator.gameObject,Out+"AmyBall.png");actions.Action=0;appearance.RefreshVisuals(0);
            clips.First(c=>c.name=="Idle").SampleAnimation(animator.gameObject,0);Require(face.position.y>foot.position.y+.5f,"Sonia debout");animator.enabled=true;animator.cullingMode=AnimatorCullingMode.AlwaysAnimate;animator.Rebind();animator.SetBool("Grounded",true);animator.SetInteger("Action",0);animator.SetFloat("GroundSpeed",0);animator.SetFloat("NormalSpeed",20);animator.Update(.2f);Require(face.position.y>foot.position.y+.5f,"Sonia debout apres Rebind");
            animator.SetFloat("GroundSpeed",65);for(int i=0;i<30;i++){animator.Update(1f/30);foreach(var pose in facial)pose.Check("Controleur course");}var q=foot.localRotation;animator.Update(.1f);Require(Quaternion.Angle(q,foot.localRotation)>.01f,"Course animee par le controleur");
            report.AppendLine("PASS visage stable, animations, boule, degats, controleur et textures.");UnityEngine.Object.DestroyImmediate(root);
            var catalog=SonicNewLevelCatalog.Load();Require(catalog.Find("sonia")?.prefab==prefab&&catalog.characters.Count(c=>c.id=="sonia")==1,"Sonia dans New Level une seule fois");Require(Resources.Load<GameObject>("Sonia")==null,"Aucun prefab Histoire Sonia");var route=Resources.Load<SonicStoryRoute>("SonicStoryRoute");Require(!route||!route.stages.Any(s=>s.character=="sonia"),"Aucun parcours Histoire Sonia");
            var spawn=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/BumperEngineV1/PlayerPrefabs/PO_Mania.prefab"),scene);var before=spawn.GetComponentInChildren<PlayerBhysics>();var position=before.transform.position;var install=typeof(SonicNewLevelSession).GetMethod("InstallCharacter",BindingFlags.Static|BindingFlags.NonPublic);var installed=(PlayerBhysics)install.Invoke(null,new object[]{scene,catalog.Find("sonia"),true});Require(installed&&Vector3.Distance(installed.transform.position,position)<.001f&&installed.GetComponent<ActionManager>().AvailableAbilities==SonicAbility.All,"Installation New Level et depart");Require(installed.TopSpeed==original.TopSpeed&&installed.MaxSpeed==original.MaxSpeed,"Vitesses New Level");Require(installed.GetComponentInChildren<SonicSoundsControl>(true).JumpingVoiceClips.Length==0,"Installation sans voix");var cam=installed.GetComponent<CameraControl>().Cam;Require(cam&&cam.transform.IsChildOf(installed.transform.root),"Camera interne");report.AppendLine("PASS New Level uniquement, capacites All, vitesses "+installed.TopSpeed+"/"+installed.MaxSpeed+", sans voix.");
        }catch(Exception e){report.AppendLine("FAIL "+e);throw;}finally{EditorSceneManager.ClosePreviewScene(scene);File.WriteAllText(Out+"verification.txt",report.ToString());}
    }
    sealed class LocalPose{public readonly Transform t;readonly Vector3 p,s;readonly Quaternion q;public LocalPose(Transform t){this.t=t;p=t.localPosition;s=t.localScale;q=t.localRotation;}public void Check(string context){Require(Vector3.Distance(t.localPosition,p)<.0001f&&Vector3.Distance(t.localScale,s)<.0001f&&Quaternion.Angle(q,t.localRotation)<.05f,"Visage/cheveux deforme "+context+" "+t.name);}}
    static void Require(bool ok,string message){if(!ok)throw new Exception(message);}
    static Bounds Bounds(GameObject go){var bounds=new Bounds();bool first=true;foreach(var r in go.GetComponentsInChildren<SkinnedMeshRenderer>(true)){var mesh=r.sharedMesh;var matrices=r.bones.Select((b,i)=>b.localToWorldMatrix*mesh.bindposes[i]).ToArray();var verts=mesh.vertices;var weights=mesh.boneWeights;for(int i=0;i<verts.Length;i++){var w=weights[i];var v=verts[i];var p=matrices[w.boneIndex0].MultiplyPoint3x4(v)*w.weight0+matrices[w.boneIndex1].MultiplyPoint3x4(v)*w.weight1+matrices[w.boneIndex2].MultiplyPoint3x4(v)*w.weight2+matrices[w.boneIndex3].MultiplyPoint3x4(v)*w.weight3;if(first){bounds=new Bounds(p,Vector3.zero);first=false;}else bounds.Encapsulate(p);}}return bounds;}
    static void Render(GameObject model,string path){var preview=new PreviewRenderUtility();try{var clone=UnityEngine.Object.Instantiate(model);clone.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);foreach(var animator in clone.GetComponentsInChildren<Animator>(true))animator.enabled=false;preview.AddSingleGO(clone);var bounds=Bounds(clone.transform.Find("SoniaRig").gameObject);preview.camera.transform.position=bounds.center+new Vector3(1.7f,.8f,3)*Mathf.Max(1,bounds.size.y);preview.camera.transform.LookAt(bounds.center);Setup(preview);Save(preview,path);}finally{preview.Cleanup();}}
    static void RenderFace(GameObject model,string path,Quaternion neutral){var preview=new PreviewRenderUtility();try{var clone=UnityEngine.Object.Instantiate(model);clone.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);foreach(var a in clone.GetComponentsInChildren<Animator>(true))a.enabled=false;preview.AddSingleGO(clone);var head=clone.GetComponentsInChildren<Transform>(true).First(t=>t.name=="Head_Amy_skeleton");var delta=head.rotation*Quaternion.Inverse(neutral);var center=head.position+delta*new Vector3(0,.3f,.05f);preview.camera.transform.position=center+delta*new Vector3(.9f,.3f,2.5f);preview.camera.transform.LookAt(center,delta*Vector3.up);Setup(preview);Save(preview,path);}finally{preview.Cleanup();}}
    static void Setup(PreviewRenderUtility p){p.camera.fieldOfView=30;p.camera.nearClipPlane=.01f;p.camera.farClipPlane=100;p.camera.backgroundColor=new Color(.15f,.2f,.28f);p.camera.clearFlags=CameraClearFlags.SolidColor;p.lights[0].intensity=1.3f;p.lights[0].transform.rotation=Quaternion.Euler(35,-30,0);p.lights[1].intensity=.7f;p.lights[1].transform.rotation=Quaternion.Euler(0,140,0);p.ambientColor=new Color(.55f,.55f,.55f);}
    static void Save(PreviewRenderUtility p,string path){p.BeginStaticPreview(new Rect(0,0,640,640));p.Render();var texture=p.EndStaticPreview();File.WriteAllBytes(path,texture.EncodeToPNG());UnityEngine.Object.DestroyImmediate(texture);}
}
